"""initial_schema

Revision ID: 5ca399203a67
Revises: 
Create Date: 2026-02-08 15:12:09.514794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ca399203a67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_manuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_range', sa.String(length=100), nullable=True),
    sa.Column('manual_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_mb', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_version', sa.String(length=50), nullable=True),
    sa.Column('ocr_quality', sa.String(length=20), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('times_accessed', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_manuals_id'), 'equipment_manuals', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_manuals_manufacturer'), 'equipment_manuals', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_equipment_manuals_model'), 'equipment_manuals', ['model'], unique=False)
    op.create_table('troubleshooting_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_manufacturer', sa.String(length=100), nullable=False),
    sa.Column('equipment_model', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_manual_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('claude_model', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('times_served', sa.Integer(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_served', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_troubleshooting_cache_equipment_model'), 'troubleshooting_cache', ['equipment_model'], unique=False)
    op.create_index(op.f('ix_troubleshooting_cache_error_code'), 'troubleshooting_cache', ['error_code'], unique=False)
    op.create_index(op.f('ix_troubleshooting_cache_id'), 'troubleshooting_cache', ['id'], unique=False)
    op.create_index(op.f('ix_troubleshooting_cache_query_hash'), 'troubleshooting_cache', ['query_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_endpoint'), 'api_usage_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    op.create_table('equipment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_location', sa.Text(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('manual_id', sa.Integer(), nullable=True),
    sa.Column('equipment_notes', sa.Text(), nullable=True),
    sa.Column('common_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_due', sa.Date(), nullable=True),
    sa.Column('warranty_expiration', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['equipment_manuals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_profiles_id'), 'equipment_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_manufacturer'), 'equipment_profiles', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_model'), 'equipment_profiles', ['model'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_serial_number'), 'equipment_profiles', ['serial_number'], unique=False)
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('troubleshooting_cache_id', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('reported_issue', sa.Text(), nullable=False),
    sa.Column('error_codes', sa.String(length=200), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('parts_replaced', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_on_site_minutes', sa.Integer(), nullable=True),
    sa.Column('troubleshooting_time_minutes', sa.Integer(), nullable=True),
    sa.Column('repair_time_minutes', sa.Integer(), nullable=True),
    sa.Column('issue_resolved', sa.Boolean(), nullable=True),
    sa.Column('followup_required', sa.Boolean(), nullable=True),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('technician_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['equipment_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['troubleshooting_cache_id'], ['troubleshooting_cache.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_id'), 'service_history', ['id'], unique=False)
    op.create_index(op.f('ix_service_history_service_date'), 'service_history', ['service_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_history_service_date'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_id'), table_name='service_history')
    op.drop_table('service_history')
    op.drop_index(op.f('ix_equipment_profiles_serial_number'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_model'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_manufacturer'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_id'), table_name='equipment_profiles')
    op.drop_table('equipment_profiles')
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_endpoint'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_troubleshooting_cache_query_hash'), table_name='troubleshooting_cache')
    op.drop_index(op.f('ix_troubleshooting_cache_id'), table_name='troubleshooting_cache')
    op.drop_index(op.f('ix_troubleshooting_cache_error_code'), table_name='troubleshooting_cache')
    op.drop_index(op.f('ix_troubleshooting_cache_equipment_model'), table_name='troubleshooting_cache')
    op.drop_table('troubleshooting_cache')
    op.drop_index(op.f('ix_equipment_manuals_model'), table_name='equipment_manuals')
    op.drop_index(op.f('ix_equipment_manuals_manufacturer'), table_name='equipment_manuals')
    op.drop_index(op.f('ix_equipment_manuals_id'), table_name='equipment_manuals')
    op.drop_table('equipment_manuals')
    # ### end Alembic commands ###
